/**
 * This file was automatically generated by apify-schema-tools.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Actor } from 'apify';
import type { Input, MaximumPages, MaximumRetries, ProxyConfiguration, DebugMode } from './input.js';

export const DEFAULT_INPUT_VALUES = {
    "startUrls": [],
    "maxPages": 10,
    "maxRetries": 3,
    "proxy": {
        "useApifyProxy": true
    },
    "debugMode": false
} as const;

export const REQUIRED_INPUT_FIELDS_WITHOUT_DEFAULT = ["searchTerm"] as const;

export type InputWithDefaults = Input & {
  maxPages: MaximumPages;
  maxRetries: MaximumRetries;
  proxy: ProxyConfiguration;
  debugMode: DebugMode;
};

export function getInputWithDefaultValues(input?: Input | null): InputWithDefaults {
    if (Actor.isAtHome()) {
        // The platform is supposed to fill in the default values
        return input! as InputWithDefaults;
    }
    if (!input) {
        throw new Error('Input is required, because the following fields are required: ' + REQUIRED_INPUT_FIELDS_WITHOUT_DEFAULT.join(', '));
    }
    return {
        ...DEFAULT_INPUT_VALUES,
        ...input,
    };
}
