/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of URLs to scrape
 */
export type StartURLs = {
  url?: string;
}[];
/**
 * Term to search for
 */
export type SearchTerm = "example" | "test" | "sample";
export type CategoryName = string;
export type CategoryID = string;
export type CategoryURL = string;
/**
 * List of categories to filter results
 */
export type Categories = {
  name?: CategoryName;
  id?: CategoryID;
  url?: CategoryURL;
}[];
/**
 * Maximum number of pages to scrape
 */
export type MaximumPages = number;
/**
 * Maximum number of retries
 */
export type MaximumRetries = number;
/**
 * Enable debug logging
 */
export type DebugMode = boolean;

/**
 * startUrls and searchTerm are required. searchTerm must be one of the predefined values.
 */
export interface Input {
  startUrls: StartURLs;
  searchTerm: SearchTerm;
  categories?: Categories;
  maxPages?: MaximumPages;
  proxy?: ProxyConfiguration;
  maxRetries?: MaximumRetries;
  debugMode?: DebugMode;
}
/**
 * Proxy settings
 */
export interface ProxyConfiguration {
  useApifyProxy?: boolean;
}
